@php
    $documents = $event->documents;
    $typeLabels = [
        'proposal' => 'Proposal',
        'lpj' => 'LPJ',
        'invitation_letter' => 'Invitation Letter',
        'mou_partner' => 'MOU Partner',
        'certificate' => 'Certificate',
        'other' => 'Other',
    ];
    $statusLabels = [
        'draft' => 'Draft',
        'generated' => 'Generated',
        'final' => 'Final',
        'archived' => 'Archived',
        'failed' => 'Failed',
    ];
@endphp

<div class="d-flex justify-content-between align-items-start mb-4 gap-3 flex-wrap">
    <div>
        <h5 class="fw-bold mb-1">Documents</h5>
        <p class="text-muted small mb-0">Kelola file proposal, LPJ, surat, dan dokumen event lainnya.</p>
    </div>

    <div class="d-flex align-items-center gap-2 flex-wrap">
        <span class="badge bg-primary-subtle text-primary rounded-pill px-3 py-2">
            {{ $documents->count() }} document
        </span>

        @if($canManageDocument)
            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#documentModal">
                Tambah Document
            </button>
        @endif
    </div>
</div>

<!-- <div class="card border-0 shadow-sm mb-4">
    <div class="card-body p-4">
        <div class="row g-3">
            <div class="col-md-4">
                <div class="p-3 bg-light rounded-3">
                    <small class="text-muted d-block">Total Document</small>
                    <h4 class="mb-0">{{ $documents->count() }}</h4>
                </div>
            </div>
            <div class="col-md-4">
                <div class="p-3 bg-success-subtle rounded-3">
                    <small class="text-muted d-block">Final</small>
                    <h4 class="mb-0">{{ $documents->where('status', 'final')->count() }}</h4>
                </div>
            </div>
            <div class="col-md-4">
                <div class="p-3 bg-warning-subtle rounded-3">
                    <small class="text-muted d-block">Mode Akses</small>
                    <h4 class="mb-0">{{ $canManageDocument ? 'Edit' : 'Lihat Saja' }}</h4>
                </div>
            </div>
        </div>
    </div>
</div> -->

<div class="card border-0 shadow-sm">
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table align-middle mb-0">
                <thead class="table-light">
                    <tr class="small text-muted text-uppercase">
                        <th class="ps-4">Title</th>
                        <th>Type</th>
                        <th>Status</th>
                        <th>File</th>
                        <th>Generated By</th>
                        @if($canManageDocument)
                            <th class="text-end pe-4">Aksi</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    @forelse($documents as $document)
                        @php
                            $badgeClass = match ($document->status) {
                                'final' => 'bg-success-subtle text-success',
                                'generated' => 'bg-primary-subtle text-primary',
                                'draft' => 'bg-light text-dark border',
                                'archived' => 'bg-secondary-subtle text-secondary',
                                default => 'bg-danger-subtle text-danger',
                            };
                        @endphp
                        <tr>
                            <td class="ps-4">
                                <div class="fw-semibold">{{ $document->title }}</div>
                                <small class="text-muted">{{ $document->notes ?? '-' }}</small>
                            </td>
                            <td>
                                <span class="badge bg-light text-dark border">{{ $typeLabels[$document->document_type] ?? ucfirst($document->document_type) }}</span>
                            </td>
                            <td>
                                <span class="badge rounded-pill px-3 py-2 {{ $badgeClass }}">
                                    {{ $statusLabels[$document->status] ?? ucfirst($document->status) }}
                                </span>
                            </td>
                            <td>
                                @if($document->file_url)
                                    <a href="{{ $document->file_url }}"
                                    target="_blank"
                                    class="btn btn-primary">

                                        Preview
                                    </a>

                                    <a href="{{ $document->file_url }}"
                                    download
                                    class="btn btn-success">

                                        Download
                                    </a>

                                @else

                                    <span class="text-muted small">
                                        Belum ada file
                                    </span>

                                @endif
                            </td>
                            <td>
                                <div class="fw-semibold">{{ $document->creator?->name ?? '-' }}</div>
                                <small class="text-muted">{{ $document->generated_at?->format('d M Y H:i') ?? $document->created_at?->format('d M Y H:i') ?? '-' }}</small>
                            </td>
                            @if($canManageDocument)
                                <td class="text-end pe-4">
                                    <div class="d-flex justify-content-end gap-2">
                                        <button
                                            type="button"
                                            class="btn btn-sm btn-outline-primary document-edit-btn"
                                            data-id="{{ $document->id_document }}"
                                            data-type="{{ $document->document_type }}"
                                            data-title="{{ e($document->title) }}"
                                            data-file="{{ e($document->file_url) }}"
                                            data-status="{{ $document->status }}"
                                            data-notes="{{ e($document->notes) }}">
                                            Edit
                                        </button>

                                        <form method="POST"
                                              action="/events/{{ $event->id_event }}/documents/{{ $document->id_document }}"
                                              onsubmit="return confirm('Hapus document ini?')">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-sm btn-outline-danger">Hapus</button>
                                        </form>
                                    </div>
                                </td>
                            @endif
                        </tr>
                    @empty
                        <tr>
                            <td colspan="{{ $canManageDocument ? 6 : 5 }}" class="p-4 text-muted">
                                Belum ada document untuk event ini.
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

@if($canManageDocument)
    <div class="modal fade" id="documentModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content border-0 shadow-lg" style="border-radius: 20px;">
                <div class="modal-body p-4">

                    <div class="d-flex justify-content-between align-items-start mb-4">
                        <div>
                            <h4 class="fw-bold mb-1">Generate Document</h4>
                            <p class="text-muted small mb-0">
                                Form akan otomatis menyesuaikan jenis document.
                            </p>
                        </div>

                        <button type="button"
                                class="btn-close"
                                data-bs-dismiss="modal"></button>
                    </div>

                    <form
                        method="POST"
                        action="/events/{{ $event->id_event }}/documents"
                        enctype="multipart/form-data">
                        @csrf

                        <div class="row g-3">

                            <!-- DOCUMENT TYPE -->
                            <div class="col-md-6">
                                <label class="form-label small text-muted">
                                    Jenis Document
                                </label>

                                <select
                                    name="document_type"
                                    id="documentType"
                                    class="form-select"
                                    required>

                                    <option value="proposal">Proposal</option>
                                    <option value="lpj">Laporan Pertanggungjawaban</option>
                                    <option value="invitation_letter">Invitation Letter</option>
                                    <option value="mou_partner">MOU</option>
                                </select>
                            </div>

                            <!-- STATUS -->
                            <div class="col-md-6">
                                <label class="form-label small text-muted">
                                    Status
                                </label>

                                <select
                                    name="status"
                                    class="form-select"
                                    required>

                                    @foreach($statusLabels as $key => $label)
                                        <option value="{{ $key }}">
                                            {{ $label }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <!-- TITLE -->
                            <div class="col-12">
                                <label class="form-label small text-muted">
                                    Document Title
                                </label>

                                <input
                                    type="text"
                                    name="title"
                                    class="form-control"
                                    placeholder="Contoh: Proposal Seminar AI"
                                    required>
                            </div>

                            <!-- DYNAMIC FORM -->
                            <div id="dynamicDocumentFields" class="row g-3"></div>

                            <!-- FILE URL -->
                            <!-- <div class="col-12">
                                <label class="form-label small text-muted">
                                    File URL
                                </label>

                                <input
                                    type="text"
                                    name="file_url"
                                    class="form-control"
                                    placeholder="https://...">
                            </div> -->

                            <!-- NOTES -->
                            <div class="col-12">
                                <label class="form-label small text-muted">
                                    Notes
                                </label>

                                <textarea
                                    name="notes"
                                    rows="3"
                                    class="form-control"
                                    placeholder="Tambahan informasi document"></textarea>
                            </div>
                        </div>

                        <div class="d-flex gap-2 mt-4">
                            <button
                                type="button"
                                class="btn btn-light flex-fill"
                                data-bs-dismiss="modal">

                                Cancel
                            </button>

                            <button
                                type="submit"
                                class="btn btn-primary flex-fill">

                                Generate Document
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>

        const dynamicDocumentFields = {

           proposal: `
                <div class="col-12">
                    <label class="form-label small text-muted">
                        Nama Event
                    </label>

                    <input
                        type="text"
                        name="event_name"
                        class="form-control"
                        value="{{ $event->nama_event }}"
                        placeholder="Nama event">
                </div>

                <div class="col-md-6">
                    <label class="form-label small text-muted">
                        Nama Organisasi
                    </label>

                    <input
                        type="text"
                        name="organization_name"
                        class="form-control"
                        value="{{ $event->organization?->nama_org ?? '' }}"
                        placeholder="Contoh: KMK ISTTS">
                </div>

                <div class="col-md-6">
                    <label class="form-label small text-muted">
                        Logo Organisasi
                    </label>

                    <input
                        type="file"
                        name="organization_logo"
                        class="form-control"
                        accept="image/*">
                </div>

                <div class="col-md-6">
                    <label class="form-label small text-muted">
                        Tahun Akademik
                    </label>

                    <input
                        type="text"
                        name="academic_year"
                        class="form-control"
                        placeholder="2025/2026">
                </div>

                <div class="col-md-4">
                    <label class="form-label small text-muted">
                        Target SMA/SMK
                    </label>

                    <input
                        type="number"
                        name="target_sma"
                        class="form-control"
                        value="0">
                </div>

                <div class="col-md-4">
                    <label class="form-label small text-muted">
                        Target Mahasiswa
                    </label>

                    <input
                        type="number"
                        name="target_mahasiswa"
                        class="form-control"
                        value="0">
                </div>

                <div class="col-md-4">
                    <label class="form-label small text-muted">
                        Target Umum
                    </label>

                    <input
                        type="number"
                        name="target_umum"
                        class="form-control"
                        value="0">
                </div>

                <div class="col-12">
                    <label class="form-label small text-muted">
                        Latar Belakang
                    </label>

                    <textarea
                        name="background_text"
                        class="form-control"
                        rows="4"></textarea>
                </div>

                <div class="col-12">
                    <label class="form-label small text-muted">
                        Tujuan Kegiatan
                    </label>

                    <textarea
                        name="objectives"
                        class="form-control"
                        rows="4"></textarea>
                </div>

                <div class="col-md-6">
                    <label class="form-label small text-muted">
                        Tanggal Event
                    </label>

                    <input
                        type="date"
                        name="event_date"
                        value="{{ $event->tgl_mulai ? \Carbon\Carbon::parse($event->tgl_mulai)->format('Y-m-d') : '' }}"
                        class="form-control">
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label class="form-label small text-muted">
                            Waktu Mulai
                        </label>

                        <input
                            type="time"
                            name="start_time"
                            class="form-control">
                    </div>

                    <div class="col-md-6">
                        <label class="form-label small text-muted">
                            Waktu Selesai
                        </label>

                        <input
                            type="time"
                            name="end_time"
                            class="form-control">
                    </div>
                </div>
                
                <div class="col-md-6">
                    <label class="form-label small text-muted">
                        Jumlah Tanda Tangan
                    </label>

                    <select
                        name="signature_count"
                        class="form-select">

                        <option value="2">2 TTD</option>
                        <option value="4">4 TTD</option>
                    </select>
                </div>

                <div class="col-12">
                    <label class="form-label small text-muted">
                        Tempat
                    </label>

                    <input
                        type="text"
                        name="venue"
                        class="form-control"
                        placeholder="Lokasi kegiatan">
                </div>

                <div class="col-12">
                    <label class="form-label small text-muted">
                        Deskripsi Kegiatan
                    </label>

                    <textarea
                        name="description_text"
                        class="form-control"
                        rows="4"></textarea>
                </div>
            `,

            lpj: `
                <div class="col-12">
                    <label class="form-label small text-muted">
                        Nama Event
                    </label>

                    <input
                        type="text"
                        name="event_name"
                        value="{{ $event->nama_event }}"
                        class="form-control">
                </div>

                <div class="col-md-6">
                    <label class="form-label small text-muted">
                        Jumlah Peserta
                    </label>

                    <input
                        type="number"
                        name="participant_count"
                        value="0"
                        class="form-control">
                </div>

                <div class="col-md-6">
                    <label class="form-label small text-muted">
                        Tanggal Realisasi
                    </label>

                    <input
                        type="date"
                        name="realization_date"
                        value="{{ $event->tgl_mulai ? \Carbon\Carbon::parse($event->tgl_mulai)->format('Y-m-d') : '' }}"
                        class="form-control">
                </div>

                <div class="col-12">
                    <label class="form-label small text-muted">
                        Tempat Realisasi
                    </label>

                    <input
                        type="text"
                        name="realized_venue"
                        class="form-control"
                        placeholder="Lokasi pelaksanaan">
                </div>

                <div class="col-12">
                    <label class="form-label small text-muted">
                        Pelaksanaan Acara
                    </label>

                    <textarea
                        name="implementation"
                        class="form-control"
                        rows="5"></textarea>
                </div>

                <div class="col-12">
                    <label class="form-label small text-muted">
                        Evaluasi
                    </label>

                    <textarea
                        name="evaluation"
                        class="form-control"
                        rows="4"></textarea>
                </div>
            `,

            invitation_letter: `
                <div class="row g-3">
                    <!-- ORGANIZER INFORMATION & LOGO -->
                    <div class="col-12">
                        <h5 class="border-bottom pb-2 text-primary font-weight-bold">1. Organizer Profile & Letterhead</h5>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted font-weight-bold">Organization / Community Name</label>
                        <input type="text" name="organization_name" value="{{ $event->organization?->nama_org ?? 'Google Developer Group Surabaya' }}" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted font-weight-bold">Official Website URL (Optional)</label>
                        <input type="text" name="organization_url" placeholder="e.g. https://gdg.community.dev/gdg-surabaya/" class="form-control">
                    </div>
                    <div class="col-12">
                        <label class="form-label small text-muted font-weight-bold">Upload Organizer Logo</label>
                        <input type="file" name="organization_logo" class="form-control" accept="image/*">
                        <div class="form-text text-muted small">Select a transparent PNG/JPG logo file to print on the top-left of the letterhead.</div>
                    </div>

                    <!-- LETTER METADATA -->
                    <div class="col-12 mt-4">
                        <h5 class="border-bottom pb-2 text-primary font-weight-bold">2. Document Metadata</h5>
                    </div>
                    <div class="col-md-4">
                        <label class="form-label small text-muted">Letter Number</label>
                        <input type="text" name="letter_number" value="060/GDG/INV/X/2026" class="form-control" required>
                    </div>
                    <div class="col-md-4">
                        <label class="form-label small text-muted">Attachment</label>
                        <input type="text" name="attachment" value="-" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label class="form-label small text-muted">Date Sent</label>
                        <input type="date" name="date_sent" value="{{ date('Y-m-d') }}" class="form-control" required>
                    </div>
                    <div class="col-12">
                        <label class="form-label small text-muted font-weight-bold">Subject / Purpose of Letter</label>
                        <input type="text" name="subject" value="Invitation as Speaker" class="form-control" required>
                    </div>

                    <!-- RECIPIENT INFORMATION -->
                    <div class="col-12 mt-4">
                        <h5 class="border-bottom pb-2 text-primary font-weight-bold">3. Recipient Information</h5>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Recipient Name</label>
                        <input type="text" name="recipient_name" value="Mr. Ibnu Sina Wardy" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Recipient Title / Affiliation</label>
                        <input type="text" name="recipient_role" value="CTO @Carte WMS & Google Developer Expert @Cloud & AI" class="form-control" required>
                    </div>

                    <!-- EVENT DETAILS -->
                    <div class="col-12 mt-4">
                        <h5 class="border-bottom pb-2 text-primary font-weight-bold">4. Event Execution Details</h5>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Event Name</label>
                        <input type="text" name="event_name" value="{{ $event->nama_event }}" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Event Date</label>
                        <input type="date" name="event_date" value="{{ $event->tgl_mulai ? \Carbon\Carbon::parse($event->tgl_mulai)->format('Y-m-d') : '' }}" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Event Time Range</label>
                        <input type="text" name="event_time" value="13:00 - 18:00 WIB" class="form-control" required>
                    </div>
                    <div class="col-md-9">
                        <label class="form-label small text-muted">Venue (Room & Detailed Address)</label>
                        <input type="text" name="event_location" value="Institut Sains dan Teknologi Terpadu Surabaya (ISTTS) Jl. Ngagel Jaya Tengah No. 73-77, Surabaya" class="form-control" required>
                    </div>
                    <div class="col-md-3">
                        <label class="form-label small text-muted">Expected Participants</label>
                        <input type="number" name="participant_total" value="100" class="form-control" required>
                    </div>

                    <!-- NARRATION & SIGNATORY -->
                    <div class="col-12 mt-4">
                        <h5 class="border-bottom pb-2 text-primary font-weight-bold">5. Letter Narration & Signatory</h5>
                    </div>
                    <div class="col-12">
                        <label class="form-label small text-muted font-weight-bold">Additional Event Description / Collaboration Details</label>
                        <textarea name="additional_description" class="form-control" rows="4" required>Flutter Fusion Conference is a collaborative initiative by Google Developer Groups (GDG) Surabaya, AI/ML Surabaya, and Flutter Surabaya. It explores "Fusion"—the synergy between Flutter (Frontend), AI (Intelligence), and Cloud (Backend)—empowering our community to build the next generation of innovative solutions.</textarea>
                        <div class="form-text text-muted small">This paragraph will be dynamically embedded in the main invitation body.</div>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Sender Name (Signatory)</label>
                        <input type="text" name="sender_name" value="Esther Irawati Setiawan" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Sender Position / Title</label>
                        <input type="text" name="sender_role" placeholder="Leave empty for auto-generated 'Lead [Event Name]'" class="form-control">
                    </div>
                </div>
            `,

            mou_partner: `
                <div class="row g-3">
                    <!-- INFO DOKUMEN -->
                    <div class="col-12">
                        <h5 class="border-bottom pb-2 text-primary font-weight-bold">1. Informasi Umum Perjanjian</h5>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted font-weight-bold">Tempat Penandatanganan MoU (Kota)</label>
                        <input type="text" name="signing_place"  class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted font-weight-bold">Tanggal Penandatanganan MoU</label>
                        <input type="date" name="signing_date" value="{{ date('Y-m-d') }}" class="form-control" required>
                    </div>

                    <!-- PIHAK PERTAMA -->
                    <div class="col-12 mt-4">
                        <h5 class="border-bottom pb-2 text-primary font-weight-bold">2. Profil Pihak Pertama (Internal)</h5>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Nama Lembaga Pihak Pertama</label>
                        <input type="text" name="first_party_name" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Nama Representatif Pihak Pertama</label>
                        <input type="text" name="first_party_representative" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Jabatan Representatif</label>
                        <input type="text" name="first_party_role"class="form-control" required>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Alamat Kantor</label>
                        <input type="text" name="first_party_address"  class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Email Resmi</label>
                        <input type="email" name="first_party_email" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">No. Telepon</label>
                        <input type="text" name="first_party_phone"  class="form-control" required>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Bertindak Selaku (Peran Legal)</label>
                        <input type="text" name="first_party_action_as" class="form-control" required>
                    </div>

                    <!-- PIHAK KEDUA -->
                    <div class="col-12 mt-4">
                        <h5 class="border-bottom pb-2 text-primary font-weight-bold">3. Profil Pihak Kedua (Mitra/Partner)</h5>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Nama Lembaga Pihak Kedua</label>
                        <input type="text" name="second_party_name" placeholder="cth. Google Developer Student Clubs Surabaya" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Nama Representatif Pihak Kedua</label>
                        <input type="text" name="second_party_representative" placeholder="cth. Alvin" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Jabatan Representatif</label>
                        <input type="text" name="second_party_role" placeholder="cth. Lead GDG On Campus" class="form-control" required>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Alamat Kantor/Instansi</label>
                        <input type="text" name="second_party_address" placeholder="Masukkan alamat lengkap mitra" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Email Mitra</label>
                        <input type="email" name="second_party_email" placeholder="Masukkan email mitra" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">No. Telepon Mitra</label>
                        <input type="text" name="second_party_phone" placeholder="Masukkan nomor telepon" class="form-control" required>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Bertindak Selaku (Peran Legal)</label>
                        <input type="text" name="second_party_action_as" placeholder="cth. Perwakilan Utama GDSC Institut STTS" class="form-control" required>
                    </div>

                    <!-- DETAIL KERJA SAMA -->
                    <div class="col-12 mt-4">
                        <h5 class="border-bottom pb-2 text-primary font-weight-bold">4. Detail Kontrak & Kerja Sama</h5>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Judul / Bentuk Kerja Sama</label>
                        <input type="text" name="cooperation_title" placeholder="cth. Penyelenggaraan Seminar Gabungan" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Waktu Pelaksanaan</label>
                        <input type="text" name="cooperation_time" placeholder="cth. Jumat, 5 Desember 2025" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted">Tempat Pelaksanaan</label>
                        <input type="text" name="cooperation_venue" placeholder="cth. Auditorium ISTTS" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted font-weight-bold">Tanggal Mulai Berlaku MoU</label>
                        <input type="date" name="start_date" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label small text-muted font-weight-bold">Tanggal Berakhir MoU</label>
                        <input type="date" name="end_date" class="form-control" required>
                    </div>
                    
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Tujuan Kerja Sama</label>
                        <textarea name="cooperation_purpose" class="form-control" rows="3" placeholder="cth. mensinergikan potensi kedua lembaga dalam peningkatan mutu pendidikan..." required></textarea>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Lingkup Kerja Sama</label>
                        <textarea name="cooperation_scope" class="form-control" rows="3" placeholder="cth. penyediaan pemateri, kerja sama publikasi, dan penyediaan fasilitas bersama..." required></textarea>
                    </div>

                    <!-- TANGGUNG JAWAB -->
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Kewajiban & Tanggung Jawab Pihak Pertama</label>
                        <textarea name="obligations_first_party" class="form-control" rows="3" placeholder="cth. menyediakan ruang auditorium, menyiapkan logistik acara..." required></textarea>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label small text-muted">Kewajiban & Tanggung Jawab Pihak Kedua</label>
                        <textarea name="obligations_second_party" class="form-control" rows="3" placeholder="cth. mengirimkan perwakilan pembicara, menyediakan materi publikasi..." required></textarea>
                    </div>
                </div>     
            `
        };

        function renderDocumentFields() {

            const type = document.getElementById('documentType').value;

            document.getElementById('dynamicDocumentFields').innerHTML =
                dynamicDocumentFields[type] || '';
        }

        document
            .getElementById('documentType')
            .addEventListener('change', renderDocumentFields);

        renderDocumentFields();

    </script>

    <div class="modal fade" id="editDocumentModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content border-0 shadow-lg" style="border-radius: 20px;">
                <div class="modal-body p-4">
                    <h5 class="fw-bold mb-3">Edit Document</h5>

                    <form id="editDocumentForm" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="row g-3">
                            <div class="col-6">
                                <label class="form-label small text-muted">Type</label>
                                <select name="document_type" id="edit_document_type" class="form-select" required>
                                    @foreach($typeLabels as $key => $label)
                                        <option value="{{ $key }}">{{ $label }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-6">
                                <label class="form-label small text-muted">Status</label>
                                <select name="status" id="edit_document_status" class="form-select" required>
                                    @foreach($statusLabels as $key => $label)
                                        <option value="{{ $key }}">{{ $label }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-12">
                                <label class="form-label small text-muted">Title</label>
                                <input type="text" name="title" id="edit_document_title" class="form-control" required>
                            </div>
                            <div class="col-12">
                                <label class="form-label small text-muted">File URL</label>
                                <input type="text" name="file_url" id="edit_document_file" class="form-control" placeholder="https://...">
                            </div>
                            <div class="col-12">
                                <label class="form-label small text-muted">Notes</label>
                                <textarea name="notes" id="edit_document_notes" class="form-control" rows="3"></textarea>
                            </div>
                        </div>

                        <div class="d-flex gap-2 mt-4">
                            <button type="button" class="btn btn-light flex-fill" data-bs-dismiss="modal">Batal</button>
                            <button type="submit" class="btn btn-primary flex-fill">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endif

@if($canManageDocument)
    <script>
        document.querySelectorAll('.document-edit-btn').forEach((btn) => {
            btn.addEventListener('click', function () {
                const form = document.getElementById('editDocumentForm');
                form.action = `/events/{{ $event->id_event }}/documents/${this.dataset.id}`;

                document.getElementById('edit_document_type').value = this.dataset.type;
                document.getElementById('edit_document_status').value = this.dataset.status;
                document.getElementById('edit_document_title').value = this.dataset.title;
                document.getElementById('edit_document_file').value = this.dataset.file || '';
                document.getElementById('edit_document_notes').value = this.dataset.notes || '';

                const modal = new bootstrap.Modal(document.getElementById('editDocumentModal'));
                modal.show();
            });
        });
    </script>
@endif
