@php
    $documents = $event->documents;
    $typeLabels = [
        'proposal' => 'Proposal',
        'lpj' => 'LPJ',
        'invitation_letter' => 'Invitation Letter',
        'mou_partner' => 'MOU Partner',
        'certificate' => 'Certificate',
        'other' => 'Other',
    ];
    $statusLabels = [
        'draft' => 'Draft',
        'generated' => 'Generated',
        'final' => 'Final',
        'archived' => 'Archived',
        'failed' => 'Failed',
    ];
@endphp

<style>
    .gform-scroll-container::-webkit-scrollbar {
        width: 6px;
    }

    .gform-scroll-container::-webkit-scrollbar-track {
        background: #f1f1f1;
        border-radius: 10px;
    }

    .gform-scroll-container::-webkit-scrollbar-thumb {
        background: #cbd5e1;
        border-radius: 10px;
    }

    .gform-scroll-container::-webkit-scrollbar-thumb:hover {
        background: #94a3b8;
    }

    .form-step {
        transition: opacity 0.2s ease-in-out;
    }

    .form-control-sm,
    .form-select-sm {
        border-radius: 8px !important;
        font-size: 0.85rem !important;
        padding: 10px 14px !important;
        border: 1.5px solid #e2e8f0 !important;
        background-color: #ffffff !important;
    }

    .form-control-sm:focus,
    .form-select-sm:focus {
        border-color: #4f46e5 !important;
        box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1) !important;
        background-color: #ffffff !important;
    }

    .style-table-card {
        border: 1px solid #e2e8f0;
        border-radius: 12px;
        overflow: hidden;
    }
</style>

<div class="d-flex justify-content-between align-items-start mb-4 gap-3 flex-wrap">
    <div>
        <h5 class="fw-bold mb-1">Documents</h5>
        <p class="text-muted small mb-0">Kelola file proposal, LPJ, surat, dan dokumen event lainnya.</p>
    </div>

    <div class="d-flex align-items-center gap-2 flex-wrap">
        <span class="badge bg-primary-subtle text-primary rounded-pill px-3 py-2">
            {{ $documents->count() }} document
        </span>

        @if ($canManageDocument)
            <button class="btn btn-primary btn-sm px-3 fw-semibold" data-bs-toggle="modal" data-bs-target="#documentModal"
                style="background-color: #4f46e5; border: none; border-radius: 8px; padding-top: 8px; padding-bottom: 8px;">
                Tambah Document
            </button>
        @endif
    </div>
</div>

<div class="card border-0 style-table-card shadow-sm">
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table align-middle mb-0" style="font-size: 0.85rem;">
                <thead class="table-light">
                    <tr class="small text-secondary text-uppercase" style="font-size: 0.75rem; letter-spacing: 0.5px;">
                        <th class="ps-4 py-2">Title</th>
                        <th class="py-2">Type</th>
                        <th class="py-2">Status</th>
                        <th class="py-2">File</th>
                        <th class="py-2">Generated By</th>
                        @if ($canManageDocument)
                            <th class="text-end pe-4 py-2">Aksi</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    @forelse($documents as $document)
                        @php
                            $badgeClass = match ($document->status) {
                                'final' => 'bg-success-subtle text-success',
                                'generated' => 'bg-primary-subtle text-primary',
                                'draft' => 'bg-light text-dark border',
                                'archived' => 'bg-secondary-subtle text-secondary',
                                default => 'bg-danger-subtle text-danger',
                            };
                        @endphp
                        <tr>
                            <td class="ps-4 py-25">
                                <div class="fw-semibold text-dark">{{ $document->title }}</div>
                                <small class="text-muted">{{ $document->notes ?? '-' }}</small>
                            </td>
                            <td class="py-25">
                                <span class="badge bg-white text-secondary border px-2 py-1"
                                    style="font-size: 0.725rem;">{{ $typeLabels[$document->document_type] ?? ucfirst($document->document_type) }}</span>
                            </td>
                            <td class="py-25">
                                <span class="badge rounded-pill px-3 py-15 fw-bold {{ $badgeClass }}"
                                    style="font-size: 10px;">
                                    {{ $statusLabels[$document->status] ?? ucfirst($document->status) }}
                                </span>
                            </td>
                            <td class="py-25">
                                @if ($document->file_url)
                                    <div class="d-flex gap-1">
                                        <a href="{{ $document->file_url }}" target="_blank"
                                            class="btn btn-xs btn-outline-primary px-2 py-1 small fw-semibold"
                                            style="font-size: 0.775rem; border-radius: 6px;">Preview</a>
                                        <a href="{{ $document->file_url }}" download
                                            class="btn btn-xs btn-light border px-2 py-1 small fw-semibold"
                                            style="font-size: 0.775rem; border-radius: 6px;">Download</a>
                                    </div>
                                @else
                                    <span class="text-muted small" style="font-size: 0.75rem;">Belum ada file</span>
                                @endif
                            </td>
                            <td class="py-25">
                                <div class="fw-semibold text-dark">{{ $document->creator?->name ?? '-' }}</div>
                                <small class="text-muted"
                                    style="font-size: 0.75rem;">{{ $document->generated_at?->format('d M Y H:i') ?? ($document->created_at?->format('d M Y H:i') ?? '-') }}</small>
                            </td>
                            @if ($canManageDocument)
                                <td class="text-end pe-4 py-25">
                                    <div class="d-flex justify-content-end gap-2">
                                        <button type="button"
                                            class="btn btn-sm btn-link text-warning p-0 text-decoration-none fw-semibold document-edit-btn"
                                            style="font-size: 0.8rem;" data-id="{{ $document->id_document }}"
                                            data-type="{{ $document->document_type }}"
                                            data-title="{{ e($document->title) }}"
                                            data-file="{{ e($document->file_url) }}"
                                            data-status="{{ $document->status }}"
                                            data-notes="{{ e($document->notes) }}">
                                            Edit
                                        </button>

                                        <button type="button"
                                            class="btn btn-sm btn-link text-danger p-0 text-decoration-none fw-semibold document-delete-btn"
                                            style="font-size: 0.8rem;" data-id="{{ $document->id_document }}"
                                            data-title="{{ e($document->title) }}">
                                            Hapus
                                        </button>
                                    </div>
                                </td>
                            @endif
                        </tr>
                    @empty
                        <tr>
                            <td colspan="{{ $canManageDocument ? 6 : 5 }}" class="p-4 text-muted text-center small">
                                Belum ada document untuk event ini.
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

@if ($canManageDocument)
    <div class="modal fade" id="documentModal" tabindex="-1" aria-hidden="true" data-bs-backdrop="static">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content border-0 shadow-lg" style="border-radius: 16px;">
                <div class="modal-body p-4">

                    <div class="d-flex justify-content-between align-items-start mb-2">
                        <div>
                            <h5 class="fw-bold text-dark mb-0" style="font-size: 1.15rem; letter-spacing: -0.3px;">
                                Generate Document</h5>
                            <p class="text-muted small mb-0" id="stepIndicator">Langkah 1 dari 2: Informasi Dasar</p>
                        </div>
                        <button type="button" class="btn-close small shadow-none" data-bs-dismiss="modal"></button>
                    </div>

                    <div class="progress mb-4" style="height: 5px;">
                        <div class="progress-bar bg-primary" id="formProgressBar" role="progressbar"
                            style="width: 50%; background-color: #4f46e5 !important;"></div>
                    </div>

                    <form method="POST" action="/events/{{ $event->id_event }}/documents"
                        enctype="multipart/form-data" id="multiStepForm">
                        @csrf

                        <div class="form-step" id="step1">
                            <div class="row g-2">
                                <div class="col-md-6">
                                    <label class="form-label small fw-semibold text-secondary mb-1">Jenis
                                        Document</label>
                                    <select name="document_type" id="documentType"
                                        class="form-select form-select-sm @error('document_type') is-invalid @enderror">
                                        <option value="proposal"
                                            {{ old('document_type') == 'proposal' ? 'selected' : '' }}>Proposal
                                        </option>
                                        <option value="lpj" {{ old('document_type') == 'lpj' ? 'selected' : '' }}>
                                            Laporan Pertanggungjawaban</option>
                                        <option value="invitation_letter"
                                            {{ old('document_type') == 'invitation_letter' ? 'selected' : '' }}>
                                            Invitation Letter</option>
                                        <option value="mou_partner"
                                            {{ old('document_type') == 'mou_partner' ? 'selected' : '' }}>MOU Partner
                                        </option>
                                    </select>
                                    @error('document_type')
                                        <div class="invalid-feedback fw-medium mt-1" style="font-size: 0.75rem;">
                                            {{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label small fw-semibold text-secondary mb-1">Status</label>
                                    <select name="status" class="form-select form-select-sm">
                                        @foreach ($statusLabels as $key => $label)
                                            <option value="{{ $key }}">{{ $label }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-12">
                                    <label class="form-label small fw-semibold text-secondary mb-1">Document
                                        Title</label>
                                    <input type="text" name="title" id="documentTitleInput"
                                        class="form-control form-control-sm"
                                        placeholder="Contoh: Proposal Master Seminar AI" value="{{ old('title') }}">
                                    <div class="invalid-feedback fw-medium mt-1" id="titleErrorFeedback"
                                        style="font-size: 0.75rem;">
                                        Mohon masukkan 'Document Title' terlebih dahulu sebelum melangkah ke halaman
                                        berikutnya.
                                    </div>
                                </div>
                                <div class="col-12">
                                    <label class="form-label small fw-semibold text-secondary mb-1">Notes</label>
                                    <textarea name="notes" rows="3" class="form-control form-control-sm"
                                        placeholder="Tambahan catatan arsip internal..."></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="form-step d-none" id="step2">
                            <div id="dynamicDocumentFields" class="row g-2 gform-scroll-container"
                                style="max-height: 52vh; overflow-y: auto; overflow-x: hidden; padding-right: 4px;">
                            </div>
                        </div>

                        <div class="form-step d-none" id="step3">
                            <div id="dynamicDocumentFieldsStep3" class="row g-2 gform-scroll-container"
                                style="max-height: 52vh; overflow-y: auto; overflow-x: hidden; padding-right: 4px;">
                            </div>
                        </div>

                        <div class="d-flex gap-2 mt-4 pt-2 border-top" style="border-color: #e2e8f0 !important;">
                            <button type="button" class="btn btn-light btn-sm px-3 fw-medium" id="btnBack"
                                data-bs-dismiss="modal"
                                style="border-radius: 8px; background-color: #f1f5f9;">Cancel</button>
                            <button type="button" class="btn btn-primary btn-sm px-4 fw-semibold" id="btnNext"
                                style="background-color: #4f46e5; border: none; border-radius: 8px;">Lanjutkan</button>
                            <button type="submit" class="btn btn-success btn-sm px-4 fw-semibold d-none"
                                id="btnSubmit" style="border-radius: 8px;">Generate Document</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        // MASTER DATA AUTOFILL MURNI DARI DATA EVENT (READ-ONLY)
        const dynamicDocumentFieldsStep2 = {
            proposal: `
                <div class="col-12">
                    <div class="p-2 mb-2 bg-light rounded border border-light small text-secondary">
                        <i class="bi bi-info-circle-fill text-primary"></i> Narasi <strong>Latar Belakang</strong> diambil otomatis dari data master Events.
                    </div>
                    <label class="form-label small fw-semibold text-secondary mb-1">Latar Belakang Event</label>
                    <textarea name="latar_belakang" class="form-control form-control-sm bg-white" rows="4" readonly style="cursor: not-allowed; color: #64748b;">{{ $event->latar_belakang ?? '' }}</textarea>
                </div>
                <div class="col-12">
                    <label class="form-label small fw-semibold text-secondary mb-1">Nama Event</label>
                    <input type="text" name="event_name" class="form-control form-control-sm" value="{{ $event->nama_event }}" placeholder="Nama event">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Nama Organisasi</label>
                    <input type="text" name="organization_name" class="form-control form-control-sm" value="{{ $event->organization?->nama_org ?? '' }}" placeholder="Contoh: SIB ISTTS">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Logo Organisasi</label>
                    <input type="file" name="organization_logo" class="form-control form-control-sm" accept="image/*">
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Tahun Akademik</label>
                    <input type="text" name="academic_year" class="form-control form-control-sm" placeholder="2025/2026" value="2025/2026">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-md-2">
                    <label class="form-label small fw-semibold text-secondary mb-1">Target SMA</label>
                    <input type="number" name="target_sma" class="form-control form-control-sm" value="0">
                </div>
                <div class="col-md-2">
                    <label class="form-label small fw-semibold text-secondary mb-1">Target Mhs</label>
                    <input type="number" name="target_mahasiswa" class="form-control form-control-sm" value="0">
                </div>
                <div class="col-md-2">
                    <label class="form-label small fw-semibold text-secondary mb-1">Target Umum</label>
                    <input type="number" name="target_umum" class="form-control form-control-sm" value="0">
                </div>
            `,

            // REKAYASA PEMISAHAN JUMLAH REALISASI PESERTA (SMA, MAHASISWA, UMUM)
            lpj: `
                <div class="col-12">
                    <label class="form-label small fw-semibold text-secondary mb-1">Nama Event</label>
                    <input type="text" name="event_name" value="{{ $event->nama_event }}" class="form-control form-control-sm">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-md-4">
                    <label class="form-label small fw-semibold text-secondary mb-1">Realisasi SMA / SMK <span class="text-danger">*</span></label>
                    <input type="number" name="target_sma" value="0" class="form-control form-control-sm" min="0">
                    <div class="invalid-feedback fw-semibold">Wajib berupa angka.</div>
                </div>
                <div class="col-md-4">
                    <label class="form-label small fw-semibold text-secondary mb-1">Realisasi Mahasiswa <span class="text-danger">*</span></label>
                    <input type="number" name="target_mahasiswa" value="0" class="form-control form-control-sm" min="0">
                    <div class="invalid-feedback fw-semibold">Wajib berupa angka.</div>
                </div>
                <div class="col-md-4">
                    <label class="form-label small fw-semibold text-secondary mb-1">Realisasi Umum <span class="text-danger">*</span></label>
                    <input type="number" name="target_umum" value="0" class="form-control form-control-sm" min="0">
                    <div class="invalid-feedback fw-semibold">Wajib berupa angka.</div>
                </div>
                <div class="col-md-12">
                    <label class="form-label small fw-semibold text-secondary mb-1">Tanggal Realisasi Acara</label>
                    <input type="date" name="realization_date" value="{{ $event->tgl_mulai ? \Carbon\Carbon::parse($event->tgl_mulai)->format('Y-m-d') : '' }}" class="form-control form-control-sm">
                    <div class="invalid-feedback fw-semibold">Pilih tanggal realisasi.</div>
                </div>
                <div class="col-12">
                    <label class="form-label small fw-semibold text-secondary mb-1">Tempat Realisasi Gedung/Ruang</label>
                    <input type="text" name="realized_venue" class="form-control form-control-sm" placeholder="Contoh: Auditorium Lantai 6 Kampus ISTTS">
                    <div class="col-md-6">
    <label class="form-label small fw-semibold text-secondary mb-1">
        Jumlah Tanda Tangan
    </label>

    <select name="signature_count"
        class="form-select form-select-sm">

        <option value="2">
            2 TTD (BAK & Ketua Panitia)
        </option>

        <option value="4" selected>
            4 TTD (Manager, Dekan, WR3, Ketua)
        </option>

    </select>
</div>
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-12">
                    <label class="form-label small fw-semibold text-dark mb-1">1. Laporan Pelaksanaan Acara</label>
                    <textarea name="implementation" class="form-control form-control-sm" rows="3" placeholder="Gambarkan jalannya runtunan pelaksanaan acara dari awal hingga penutupan..."></textarea>
                    <div class="invalid-feedback fw-semibold">Wajib diisi rincian pelaksanaan.</div>
                </div>
                <div class="col-12">
                    <label class="form-label small fw-semibold text-dark mb-1">2. Evaluasi Sesi Kegiatan</label>
                    <textarea name="evaluation" class="form-control form-control-sm" rows="3" placeholder="Tuliskan kendala teknis lapangan yang dihadapi panitia pelaksana..."></textarea>
                    <div class="invalid-feedback fw-semibold">Wajib diisi bahan evaluasi.</div>
                </div>
                <div class="col-12">
                    <label class="form-label small fw-semibold text-dark mb-1">3. Kritik Dokumen Pengawas</label>
                    <textarea name="kritik" class="form-control form-control-sm" rows="3" placeholder="Tuliskan kekurangan koordinasi internal antar divisi kepanitiaan..."></textarea>
                    <div class="invalid-feedback fw-semibold">Wajib diisi poin kritik.</div>
                </div>
                <div class="col-12">
                    <label class="form-label small fw-semibold text-dark mb-1">4. Saran Perbaikan Kedepan</label>
                    <textarea name="saran" class="form-control form-control-sm" rows="3" placeholder="Tuliskan rekomendasi atau backup solution untuk kepanitiaan event berikutnya..."></textarea>
                    <div class="invalid-feedback fw-semibold">Wajib diisi rekomendasi saran.</div>
                </div>
            `,

            invitation_letter: `
                <div class="col-12">
                    <h6 class="border-bottom pb-1 text-primary fw-bold small"><i class="bi bi-building me-1"></i> 1. Organizer Profile & Letterhead</h6>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Organization / Community Name</label>
                    <input type="text" name="organization_name" value="{{ $event->organization?->nama_org ?? 'Sistem Informasi Bisnis ISTTS' }}" class="form-control form-control-sm">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Official Website URL (Optional)</label>
                    <input type="text" name="organization_url" placeholder="e.g. https://istts.ac.id" class="form-control form-control-sm">
                </div>
                <div class="col-12">
                    <label class="form-label small fw-semibold text-secondary mb-1">Upload Official Logo (.png/.jpg)</label>
                    <input type="file" name="organization_logo" class="form-control form-control-sm" accept="image/*">
                </div>

                <div class="col-12 mt-2">
                    <h6 class="border-bottom pb-1 text-primary fw-bold small"><i class="bi bi-envelope-paper me-1"></i> 2. Document Metadata</h6>
                </div>
                <div class="col-md-4">
                    <label class="form-label small fw-semibold text-secondary mb-1">Letter Number</label>
                    <input type="text" name="letter_number" value="001/SIB-ISTTS/INV/VI/2026" class="form-control form-control-sm">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-md-4">
                    <label class="form-label small fw-semibold text-secondary mb-1">Attachment</label>
                    <input type="text" name="attachment" value="1 Berkas Proposal" class="form-control form-control-sm">
                </div>
                <div class="col-md-4">
                    <label class="form-label small fw-semibold text-secondary mb-1">Date Sent</label>
                    <input type="date" name="date_sent" value="{{ date('Y-m-d') }}" class="form-control form-control-sm">
                </div>
                <div class="col-12">
                    <label class="form-label small fw-semibold text-secondary mb-1">Subject / Purpose of Letter</label>
                    <input type="text" name="subject" value="Permohonan Delegasi Pembicara Seminar" class="form-control form-control-sm">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>

                <div class="col-12 mt-2">
                    <h6 class="border-bottom pb-1 text-primary fw-bold small"><i class="bi bi-person-bounding-box me-1"></i> 3. Recipient Information</h6>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Recipient Name</label>
                    <input type="text" name="recipient_name" value="Bpk. Ren Hard" class="form-control form-control-sm">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Recipient Title / Affiliation</label>
                    <input type="text" name="recipient_role" value="Lead Developer Partner Developer Studio Surabaya" class="form-control form-control-sm">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>

                <div class="col-12 mt-2">
                    <h6 class="border-bottom pb-1 text-primary fw-bold small"><i class="bi bi-clock me-1"></i> 4. Event Execution Details</h6>
                </div>
                <div class="col-md-12">
                    <label class="form-label small fw-semibold text-secondary mb-1">Event Name</label>
                    <input type="text" name="event_name" value="{{ $event->nama_event }}" class="form-control form-control-sm">
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Event Date</label>
                    <input type="date" name="event_date" value="{{ $event->tgl_mulai ? \Carbon\Carbon::parse($event->tgl_mulai)->format('Y-m-d') : '' }}" class="form-control form-control-sm">
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Event Time Range</label>
                    <input type="text" name="event_time" value="09:00 - 13:00 WIB" class="form-control form-control-sm">
                </div>
                <div class="col-md-12">
                    <label class="form-label small fw-semibold text-secondary mb-1">Venue (Detailed Address)</label>
                    <input type="text" name="event_location" value="Institut Sains dan Teknologi Terpadu Surabaya (ISTTS) Jl. Ngagel Jaya Tengah No. 73-77, Surabaya" class="form-control form-control-sm">
                </div>
            `,

            mou_partner: `
                <div class="col-12">
                    <h6 class="border-bottom pb-1 text-primary fw-bold small">1. Informasi Umum Perjanjian</h6>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Tempat Penandatanganan MoU (Kota)</label>
                    <input type="text" name="signing_place" class="form-control form-control-sm" value="Surabaya">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Tanggal Penandatanganan MoU</label>
                    <input type="date" name="signing_date" value="{{ date('Y-m-d') }}" class="form-control form-control-sm">
                </div>
                <div class="col-12 mt-2">
                    <h6 class="border-bottom pb-1 text-primary fw-bold small">2. Profil Pihak Pertama (Internal Organizer)</h6>
                </div>
                <div class="col-12">
                    <label class="form-label small fw-semibold text-secondary mb-1">Nama Lembaga Pihak Pertama</label>
                    <input type="text" name="first_party_name" value="Fakultas Sains dan Teknologi ISTTS" class="form-control form-control-sm">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Nama Representatif Pihak Pertama</label>
                    <input type="text" name="first_party_representative" class="form-control form-control-sm" placeholder="Nama koordinator pelaksana">
                    <div class="invalid-feedback fw-semibold">Field ini wajib diisi.</div>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Jabatan Representatif</label>
                    <input type="text" name="first_party_role" value="Ketua Pelaksana {{ $event->nama_event }}" class="form-control form-control-sm">
                </div>
                <div class="col-12">
                    <label class="form-label small fw-semibold text-secondary mb-1">Alamat Kantor Pihak Pertama</label>
                    <input type="text" name="first_party_address" value="Jl. Ngagel Jaya Tengah No. 73-77, Surabaya" class="form-control form-control-sm">
                </div>
            `
        };

        const dynamicDocumentFieldsStep3 = {
            proposal: `
                <div class="col-12">
                    <div class="p-2 mb-2 bg-light rounded border border-light small text-secondary">
                        <i class="bi bi-info-circle-fill text-primary"></i> Narasi <strong>Tujuan</strong> diambil otomatis dari data master Events.
                    </div>
                    <label class="form-label small fw-semibold text-secondary mb-1">Tujuan Kegiatan</label>
                    <textarea name="tujuan" class="form-control form-control-sm bg-white" rows="3" readonly style="cursor: not-allowed; color: #64748b;">{{ $event->tujuan ?? '' }}</textarea>
                </div>
                
                <div class="col-12">
                    <label class="form-label small fw-semibold text-dark mb-1">Deskripsi Ringkas Kegiatan <span class="text-danger">*</span></label>
                    <textarea name="deskripsi_kegiatan" class="form-control form-control-sm" rows="4" placeholder="Jelaskan secara ringkas konsep teknis acara, pembicara, materi, atau aktivitas utama yang akan dilakukan pada hari H..."></textarea>
                    <div class="invalid-feedback fw-semibold">Deskripsi kegiatan wajib diisi untuk kelengkapan proposal.</div>
                </div>

                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Tanggal Mulai Acara</label>
                    <input type="date" name="event_date" value="{{ $event->tgl_mulai ? \Carbon\Carbon::parse($event->tgl_mulai)->format('Y-m-d') : '' }}" class="form-control form-control-sm">
                </div>
                <div class="col-md-3">
                    <label class="form-label small fw-semibold text-secondary mb-1">Jam Mulai</label>
                    <input type="time" name="start_time" class="form-control form-control-sm" value="{{ $event->tgl_mulai ? \Carbon\Carbon::parse($event->tgl_mulai)->format('H:i') : '' }}">
                </div>
                <div class="col-md-3">
                    <label class="form-label small fw-semibold text-secondary mb-1">Jam Selesai</label>
                    <input type="time" name="end_time" class="form-control form-control-sm" value="{{ $event->tgl_selesai ? \Carbon\Carbon::parse($event->tgl_selesai)->format('H:i') : '17:00' }}">
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Susunan Lembar Pengesahan</label>
                    <select name="signature_count" class="form-select form-select-sm">
                        <option value="2">2 TTD (Ketua Panitia & Koordinator)</option>
                        <option value="4">4 TTD (Lengkap + Kaprodi & Dekan)</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label class="form-label small fw-semibold text-secondary mb-1">Lokasi Gedung / Ruangan</label>
                    <input type="text" name="venue" class="form-control form-control-sm" placeholder="Contoh: Gedung L Lantai 2 Kampus ISTTS">
                    <div class="invalid-feedback fw-semibold">Field lokasi wajib diisi.</div>
                </div>
            `
        };

        document.addEventListener("DOMContentLoaded", function() {
            let currentStep = 1;

            const step1 = document.getElementById("step1");
            const step2 = document.getElementById("step2");
            const step3 = document.getElementById("step3");

            const btnNext = document.getElementById("btnNext");
            const btnBack = document.getElementById("btnBack");
            const btnSubmit = document.getElementById("btnSubmit");

            const stepIndicator = document.getElementById("stepIndicator");
            const formProgressBar = document.getElementById("formProgressBar");
            const documentTypeSelect = document.getElementById("documentType");
            const documentTitleInput = document.getElementById("documentTitleInput");
            const titleErrorFeedback = document.getElementById("titleErrorFeedback");

            const fieldsContainerStep2 = document.getElementById("dynamicDocumentFields");
            const fieldsContainerStep3 = document.getElementById("dynamicDocumentFieldsStep3");
            const formElement = document.getElementById("multiStepForm");

            function renderDynamicFields() {
                const selectedType = documentTypeSelect.value;
                fieldsContainerStep2.innerHTML = dynamicDocumentFieldsStep2[selectedType] ||
                    `<div class="col-12 text-muted small p-3">Tidak ada field tambahan wajib untuk tipe dokumen ini.</div>`;

                fieldsContainerStep3.innerHTML = dynamicDocumentFieldsStep3[selectedType] || '';

                attachRealtimeValidationClearance();
            }

            documentTypeSelect.addEventListener("change", function() {
                renderDynamicFields();
                currentStep = 1;
                updateFormStep();
            });
            renderDynamicFields();

            function getTotalSteps() {
                return documentTypeSelect.value === 'proposal' ? 3 : 2;
            }

            function validateContainerFields(containerElement) {
                let isValid = true;
                const inputs = containerElement.querySelectorAll('input, select, textarea');

                inputs.forEach(input => {
                    if (input.type === 'file' || input.name === 'organization_url' || input.name ===
                        'sender_role' || input.readOnly) {
                        return;
                    }

                    if (input.value === null || input.value.trim() === "") {
                        input.classList.add("is-invalid");
                        const feedback = input.nextElementSibling;
                        if (feedback && feedback.classList.contains('invalid-feedback')) {
                            feedback.style.display = 'block';
                        }
                        isValid = false;
                    } else {
                        input.classList.remove("is-invalid");
                        const feedback = input.nextElementSibling;
                        if (feedback && feedback.classList.contains('invalid-feedback')) {
                            feedback.style.display = 'none';
                        }
                    }
                });

                if (!isValid) {
                    const firstInvalid = containerElement.querySelector('.is-invalid');
                    if (firstInvalid) {
                        firstInvalid.focus();
                    }
                }
                return isValid;
            }

            function attachRealtimeValidationClearance() {
                const elements = document.querySelectorAll(
                    '#multiStepForm input, #multiStepForm textarea, #multiStepForm select');
                elements.forEach(el => {
                    const clearError = function() {
                        if (this.value.trim() !== "") {
                            this.classList.remove("is-invalid");
                            const feedback = this.nextElementSibling;
                            if (feedback && feedback.classList.contains('invalid-feedback')) {
                                feedback.style.display = 'none';
                            }
                        }
                    };
                    el.addEventListener('input', clearError);
                    el.addEventListener('change', clearError);
                });
            }

            function updateFormStep() {
                const totalSteps = getTotalSteps();
                const typeLabel = documentTypeSelect.options[documentTypeSelect.selectedIndex].text;

                step1.classList.add("d-none");
                step2.classList.add("d-none");
                step3.classList.add("d-none");

                if (currentStep === 1) {
                    step1.classList.remove("d-none");
                    stepIndicator.innerText = `Langkah 1 dari ${totalSteps}: Informasi Dasar`;
                    formProgressBar.style.width = `${(1 / totalSteps) * 100}%`;
                    formProgressBar.classList.replace("bg-success", "bg-primary");

                    btnBack.innerText = "Cancel";
                    btnBack.setAttribute("data-bs-dismiss", "modal");
                    btnBack.classList.replace("btn-outline-secondary", "btn-light");

                    btnNext.classList.remove("d-none");
                    btnSubmit.classList.add("d-none");
                } else if (currentStep === 2) {
                    step2.classList.remove("d-none");

                    if (totalSteps === 3) {
                        stepIndicator.innerText = `Langkah 2 dari 3: Profil & Narasi Master`;
                        btnNext.classList.remove("d-none");
                        btnSubmit.classList.add("d-none");
                        formProgressBar.classList.replace("bg-success", "bg-primary");
                    } else {
                        stepIndicator.innerText = `Langkah 2 dari 2: Rincian Isi Dokumen ${typeLabel}`;
                        btnNext.classList.add("d-none");
                        btnSubmit.classList.remove("d-none");
                        formProgressBar.classList.replace("bg-primary", "bg-success");
                    }

                    formProgressBar.style.width = `${(2 / totalSteps) * 100}%`;
                    btnBack.innerText = "Kembali";
                    btnBack.removeAttribute("data-bs-dismiss");
                    btnBack.classList.replace("btn-light", "btn-outline-secondary");
                } else if (currentStep === 3) {
                    step3.classList.remove("d-none");
                    stepIndicator.innerText = `Langkah 3 dari 3: Pelaksanaan & Pengesahan`;
                    formProgressBar.style.width = "100%";
                    formProgressBar.classList.replace("bg-primary", "bg-success");

                    btnNext.classList.add("d-none");
                    btnSubmit.classList.remove("d-none");
                }
            }

            btnNext.addEventListener("click", function() {
                if (currentStep === 1) {
                    if (!documentTitleInput.value.trim()) {
                        documentTitleInput.classList.add("is-invalid");
                        titleErrorFeedback.style.display = "block";
                        return;
                    }
                    documentTitleInput.classList.remove("is-invalid");
                    titleErrorFeedback.style.display = "none";
                } else if (currentStep === 2) {
                    if (!validateContainerFields(fieldsContainerStep2)) {
                        return;
                    }
                }

                if (currentStep < getTotalSteps()) {
                    currentStep++;
                    updateFormStep();
                }
            });

            formElement.addEventListener("keydown", function(event) {
                if (event.key === "Enter" && event.target.tagName !== "TEXTAREA") {
                    event.preventDefault();
                    if (currentStep < getTotalSteps()) {
                        btnNext.click();
                    } else {
                        btnSubmit.click();
                    }
                }
            });

            formElement.addEventListener("submit", function(e) {
                const totalSteps = getTotalSteps();
                if (currentStep < totalSteps) {
                    e.preventDefault();
                    btnNext.click();
                    return;
                }
                if (totalSteps === 3 && currentStep === 3) {
                    if (!validateContainerFields(fieldsContainerStep3)) {
                        e.preventDefault();
                    }
                } else if (totalSteps === 2 && currentStep === 2) {
                    if (!validateContainerFields(fieldsContainerStep2)) {
                        e.preventDefault();
                    }
                }
            });

            btnBack.addEventListener("click", function(e) {
                if (currentStep > 1) {
                    e.preventDefault();
                    currentStep--;
                    updateFormStep();
                }
            });

            const documentModalEl = document.getElementById('documentModal');
            if (documentModalEl) {
                documentModalEl.addEventListener('hidden.bs.modal', function() {
                    currentStep = 1;
                    updateFormStep();
                    formElement.reset();
                    documentTitleInput.classList.remove("is-invalid");
                    titleErrorFeedback.style.display = "none";
                    renderDynamicFields();
                });
            }
        });
    </script>

    <div class="modal fade" id="editDocumentModal" tabindex="-1" aria-hidden="true" data-bs-backdrop="static">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content border-0 shadow-lg" style="border-radius: 16px;">
                <div class="modal-body p-4">
                    <div class="d-flex justify-content-between align-items-start mb-3">
                        <div>
                            <h5 class="fw-bold text-dark mb-0" style="font-size: 1.15rem; letter-spacing: -0.3px;">
                                Edit Metadata Document</h5>
                            <p class="text-muted small mb-0" style="font-size: 0.8rem;">Perbarui rincian log arsip
                                document.</p>
                        </div>
                        <button type="button" class="btn-close small shadow-none" data-bs-dismiss="modal"></button>
                    </div>

                    <form id="editDocumentForm" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="row g-2">
                            <div class="col-6">
                                <label class="form-label small fw-semibold text-secondary mb-1">Type</label>
                                <select name="document_type" id="edit_document_type"
                                    class="form-select form-select-sm">
                                    @foreach ($typeLabels as $key => $label)
                                        <option value="{{ $key }}">{{ $label }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-6">
                                <label class="form-label small fw-semibold text-secondary mb-1">Status</label>
                                <select name="status" id="edit_document_status" class="form-select form-select-sm">
                                    @foreach ($statusLabels as $key => $label)
                                        <option value="{{ $key }}">{{ $label }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-12">
                                <label class="form-label small fw-semibold text-secondary mb-1">Title</label>
                                <input type="text" name="title" id="edit_document_title"
                                    class="form-control form-control-sm" required>
                            </div>
                            <div class="col-12">
                                <label class="form-label small fw-semibold text-secondary mb-1">File URL</label>
                                <input type="text" name="file_url" id="edit_document_file"
                                    class="form-control form-control-sm" placeholder="https://...">
                            </div>
                            <div class="col-12">
                                <label class="form-label small fw-semibold text-secondary mb-1">Notes</label>
                                <textarea name="notes" id="edit_document_notes" class="form-control form-control-sm" rows="3"></textarea>
                            </div>
                        </div>

                        <div class="d-flex gap-2 mt-4">
                            <button type="button" class="btn btn-light btn-sm flex-fill fw-medium"
                                data-bs-dismiss="modal"
                                style="border-radius: 8px; background-color: #f1f5f9;">Batal</button>
                            <button type="submit" class="btn btn-primary btn-sm flex-fill fw-semibold"
                                style="border-radius: 8px; background-color: #4f46e5; border: none;">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            document.querySelectorAll('.document-edit-btn').forEach((btn) => {
                btn.addEventListener('click', function() {
                    const form = document.getElementById('editDocumentForm');
                    form.action = `/events/{{ $event->id_event }}/documents/${this.dataset.id}`;
                    document.getElementById('edit_document_type').value = this.dataset.type;
                    document.getElementById('edit_document_status').value = this.dataset.status;
                    document.getElementById('edit_document_title').value = this.dataset.title;
                    document.getElementById('edit_document_file').value = this.dataset.file || '';
                    document.getElementById('edit_document_notes').value = this.dataset.notes || '';

                    const modal = new bootstrap.Modal(document.getElementById('editDocumentModal'));
                    modal.show();
                });
            });

            document.querySelectorAll('.document-delete-btn').forEach((btn) => {
                btn.addEventListener('click', function() {
                    const form = document.getElementById('deleteDocumentForm');
                    form.action = `/events/{{ $event->id_event }}/documents/${this.dataset.id}`;
                    document.getElementById('delete_document_title_display').textContent = this
                        .dataset.title;

                    const modal = new bootstrap.Modal(document.getElementById(
                        'deleteDocumentModal'));
                    modal.show();
                });
            });
        });
    </script>

    <div class="modal fade" id="deleteDocumentModal" tabindex="-1" aria-hidden="true" data-bs-backdrop="static">
        <div class="modal-dialog modal-dialog-centered modal-sm">
            <div class="modal-content border-0 shadow-lg" style="border-radius: 16px;">
                <div class="modal-body p-4 text-center">
                    <div class="mb-3 text-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor"
                            class="bi bi-exclamation-circle-fill" viewBox="0 0 16 16">
                            <path
                                d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4m.002 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2" />
                        </svg>
                    </div>
                    <h5 class="fw-bold text-dark mb-2" style="font-size: 1.05rem;">Konfirmasi Hapus</h5>
                    <p class="text-muted small mb-4">Apakah Anda yakin ingin menghapus document <strong
                            id="delete_document_title_display" class="text-dark"></strong>? Tindakan ini permanen dan
                        tidak dapat dibatalkan.</p>
                    <form id="deleteDocumentForm" method="POST">
                        @csrf
                        @method('DELETE')
                        <div class="d-flex gap-2">
                            <button type="button" class="btn btn-light btn-sm flex-fill fw-medium"
                                data-bs-dismiss="modal" style="border-radius: 8px;">Batal</button>
                            <button type="submit" class="btn btn-danger btn-sm flex-fill fw-semibold"
                                style="border-radius: 8px;">Ya, Hapus</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endif
